Domain audit file
eigenmagic/fediblockhole pull request #55
Opened 2023-08-20 07:52 UTC by sgrigson

Allows for the creation of a Blocklist Audit File.

This audit file can be used to return metadata about each domain match, such as the number of matches by count or percentage.

(This was primarily done for my own needs, but it should be easy enough to ignore for users who do not want to use this feature, as by default it's not enabled.)

2023-09-03 20:41 UTC, jpwarren commented on src/fediblockhole/__init__.py
> +        args.blocklist_auditfile = conf.get('blocklist_auditfile', '')
I think this should return None if no `blocklist_auditfile` is set.

2023-09-03 20:53 UTC, jpwarren requested changes
Good addition, I like it.

Small change to the semantics requested: make the default audit filepath `None` instead of an empty string, then check for existence/truthiness to see if you need to save audit info.

2023-09-03 20:53 UTC, jpwarren commented on src/fediblockhole/__init__.py
> +    save_block_audit_file: str='') -> Blocklist:
Why does this string default to empty? Wouldn't a `None` be a better indicator that no audit file is needed?
I'd be worried I'd accidentally clobber some other file in the working directory by opening an empty string for writing or something.

2023-09-03 20:53 UTC, jpwarren commented on src/fediblockhole/__init__.py
> +        if len(save_block_audit_file) > 0:
Yeah, I think this check should be `if save_block_audit_file:` which will match on None or empty list/string.

Could more explicitly require `if save_block_audit_file is not None:` but a wider capture of non-useful settings (like empty strings) here probably guards more against accidentally opening a wrong logfile, and matching the user intent.

I think I'd find the first method easier to interpret after a while away from the code. It took me a moment to figure out why this needed to be a positive-length item, and it's more that it needs to be something that can be opened as a file. Let's be kind to future us.

2023-09-06 16:31 UTC, sgrigson commented
Good points! Updated and ready for another review.

I'm very new to Python (mostly working with Golang lately), so appreciate the best practice tip there about 'None'.

2023-09-06 21:14 UTC, jpwarren reviewed
Looks good!

2023-09-06 21:15 UTC, merged